# -*- coding: utf-8 -*-
"""inventory analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14aGt4QCEEFsMQ4DgoxUk3v-c0biw-0aw
"""



import json

# Get the notebook's JSON content
notebook_json = json.loads(open('/content/drive/MyDrive/Inventory Analysis.ipynb', 'r').read()) # Assuming the notebook is in MyDrive

# Extract code from code cells
code_cells_content = []
for cell in notebook_json['cells']:
    if cell['cell_type'] == 'code':
        # Join the source lines and add a separator
        code_cells_content.append("".join(cell['source']) + "\n# ---\n\n")

# Write the code to a text file
with open('all_notebook_code.py', 'w') as f:
    for code_block in code_cells_content:
        f.write(code_block)

print("All code cells have been saved to 'all_notebook_code.py'")